server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gateway
zuul:
  routes:
    teacher: /t/**